### ISSUE TITLE
--exclude filters have no effect on current working directory

### ISSUE THREAD

**Issue by zfields** [gcovr/gcovr#323]
These paths are the result of environment variable concatenation. They are absolute and used to work in 3.4.
```bash
gcovr
[...]
--exclude /home/zak/dev/GitHub/particle-iot/device-os/test/unit_tests/../../test`
--exclude /home/zak/dev/GitHub/particle-iot/device-os/test/unit_tests/../../third_party
[...]
```

**Comment by latk** [comment]
The behaviour of filters has been clarified/corrected in the 4.0 release. Unfortunately, you encountered one of the cases where the changes were not entirely backwards-compatible.

Filters are regular expressions that match paths. Before 4.0, gcovr would normalize the path, so that these three filters were mostly identical, assuming we are in the `/foo/bar` directory:

    --exclude /foo/bar/../baz
    --exclude ../baz
    --exclude /foo/baz

This is *incorrect* because filters are regular expressions, which cannot be reasonably transformed using path operations. E.g. `..` means “go to the parent directory” in a path, but “any two characters” in a regex. To reliably match a parent directory at the start of the filter, we'd have to escape as `\.\./baz` but that's impossible in the middle of a regex because the escapes prevent path normalization.

Gcovr 4.0 stopped any regex munging, and instead transforms the path to match the regex. As discussed [in the docs](https://gcovr.com/en/stable/guide.html#using-filters):

* if the regex looks like an absolute path, it is matched against the realpath of the file
* otherwises, the regex is matched against the relative path of the source file (relative to the current directory)

Your regexes look like an absolute path, but do not match the realpath.

You have three options to resolve this issue:

1. switch to relative paths in your filters.
2. use shell tools to normalize the absolute path before passing it to gcovr, e.g. `--exclude "$(realpath -- YOUR_PATH_HERE)"` with realpath from GNU coreutils and when running the Bash shell.
3. implement a gcovr mode that treats the filters as paths rather than regexes.

About 3: right now gcovr guesses whether a filter should match an absolute path. This could be made explicit by adding a filter type prefix syntax, e.g. `+rel:foo`, `+abs:/bar`. Then we can add a filter type for paths that should not be treated as a regex: `+path:/foo/../bar`. Internally, the `--root` is already treated as such a directory filter. What is missing is just the type prefix syntax.

**Comment by zfields** [comment]
Thanks for the quick response! I'm still having a bit of an issue.

I can exclude the `third_party` directory with the following filter
```bash
--exclude "(.*/)+third_party"
```
but I am unable to exclude the sibling `test` folder using the same logic
```bash
--exclude "(.*/)+test"
```

**Comment by latk** [comment]
Your regex `(.*/)+folder` requires a slash before the folder name. It matches `foo/bar/folder/whatever` but not the relative path `folder/whatever`. The `+` quantifier wants to see at least one occurrence of the group incl slash.

To fix this, change to the regex `(.*/)?folder/`. This will make the prefix optional. I also suggest including a trailing slash to ensure that the folder name ends there. If you know that the folder is in the current directory, then simply using `folder/` will be sufficient.

I think I should update the docs with some example regexes for common use cases.

**Comment by zfields** [comment]
@latk Thank you so much for offering your suggestion. Unfortunately, neither your, nor my, regex works while in the current working directory. In fact, if I increase the aggressiveness of the filter (i.e. `.*/test/.*`, `.*/coverage/.*`, etc...), it still will not filter files from the current working directory.

**Comment by latk** [comment]
The regex `.*/folder/.*` still requires the path to have a slash before the folder name and thus won't match entries in the current directory. Note that a trailing `.*` in the regex cannot change which paths are matched.

To understand your filtering needs precisely, I need an accurate description of your project layout. As I understand it:

* `/prefix/particle-iot/device-os/` – you run gcovr from this directory
* `/prefix/particle-iot/device-os/test/` – you want to exclude this directory
* `/prefix/particle-iot/device-os/src/` – you want to include this directory
* `/prefix/particle-iot/device-os/third_party/`– you want to exclude this directory

You are running the command: `gcovr --exclude '.*/test/' --exclude '.*/third_party/'`

Actual behaviour: all of the directories are included

Solution: change the filters to avoid the leading slash: `gcovr --exclude test/ --exclude third_party/` or `gcovr --root src` or `gcovr --filter src/`

That this solution didn't work indicates that my understanding of your project layout is wrong, e.g. that you are running gcovr from a different directory.

**Comment by zfields** [comment]
Very close, but not quite. And again, thank you so much for your time!

* **[NO]** `/prefix/particle-iot/device-os/` – you run gcovr from this directory
* [YES] `/prefix/particle-iot/device-os/test/` – you want to exclude this directory
* [YES] `/prefix/particle-iot/device-os/src/` – you want to include this directory
* [YES] `/prefix/particle-iot/device-os/third_party/` – you want to exclude this directory

I'm running `gcovr` from `/prefix/particle-iot/device-os/test/unit_tests/build`, like so:

```bash
gcovr --root ../../.. --exclude '(.*/)*test/+' --exclude '(.*/)*third_party/+' -j 4 --print-summary
```

**Comment by zfields** [comment]
Also, if you would like to fiddle with it yourself, it's publicly available on GitHub.

```
git clone https://github.com/particle-iot/device-os -b gcov
cd device-os/test/unit_test/
mkdir build && cd build
cmake .. && make all test coverage
```

It should all run successfully and you will see coverage reported correctly _(I used your `realpath` advice from this morning)_.

However, if you change the `gcovr` call in `device-os/test/unit_test/CMakeList.txt`, to use the regex filters you described you will be able to reproduce this issue.

**Comment by latk** [comment]
Ok, that clarifies things a lot. None of the directories you want to ignore are in the current working directory, therefore all of my talk about incorrect slashes is moot.

In your CMakeLists.txt, the correct approach is likely to construct the absolute path using CMake built-ins like [get_filename_component()](https://cmake.org/cmake/help/latest/command/get_filename_component.html):

``` cmake
get_filename_component(DEVICE_OS_DIR   ../.. ABSOLUTE BASE_DIR ${CMAKE_CURRENT_LIST_DIR})
get_filename_component(TEST_DIR        test/ ABSOLUTE BASE_DIR ${DEVICE_OS_DIR})
get_filename_component(THIRD_PARTY_DIR third_party/ ABSOLUTE BASE_DIR ${DEVICE_OS_DIR})
```

Excluding the test directory didn't work because we're in a sub-directory of the test directory. Slightly simplified:

* `/foo/test/build/` - working directory where gcovr runs
* `/foo/test/` - directory we want to ignore
* `/foo/test/bar.c` - example file we want to ignore

If we use a relative filter like `.*/test/` then we will match against the file path `../bar.c` which does not include the name of the `test` directory. The correct way to exclude the test directory would be to exclude any relative path that does not start with `../../`, e.g. `--exclude '(?!\.\./\.\./)'` – but I concede that this isn't ideal or user-friendly. In your real project you would want `../../../` instead.

If you only had a few source directories, you could have also tried a --filter (include) instead of an exclude, e.g. `--filter ../../../system --filter ../../../modules`.

But absolute paths as indicated above are the more readable and robust solution.

Thank you very much for this discussion. Questions like this help me understand what real-world users actually need.

**Comment by zfields** [comment]
Thank you breaking that down! I understand what's happening now. :+1: 

To provide some constructive feedback. I would expect `gcovr` to normalize the file paths; thus allowing the filters to work more intuitively.

I understand my request may be hard to accommodate, so it would be nice if you could elaborate in the documentation on the way `gcovr` considers paths (especially with respect to the calling directory) while applying the filters (regex).

**Comment by peter-toft-greve** [comment]
Really good thread - THANX, but I have a variant of this in https://github.com/gcovr/gcovr/issues/551 that some of you might help me with
