### ISSUE TITLE
Gcovr 5.1 with "--decisions" flag throws uncaught exception

### ISSUE THREAD

**Issue by simonCor** [gcovr/gcovr#640]
**Describe the bug**
I use gcovr on a large C++17 code base. The tests are compiled for QNX and run on an ARM QNX system.

This works fine as long as I do not add the "--decisions" flag. When we add it the following exception is thrown on all gcovr runs:
```
Traceback (most recent call last):
  File "c:\users\public\programme\python\lib\site-packages\gcovr\workers.py", line 77, in worker
    work(*args, **kwargs)
  File "c:\users\public\programme\python\lib\site-packages\gcovr\gcov.py", line 317, in process_datafile
    done = run_gcov_and_process_files(
  File "c:\users\public\programme\python\lib\site-packages\gcovr\gcov.py", line 490, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "c:\users\public\programme\python\lib\site-packages\gcovr\gcov.py", line 152, in process_gcov_data
    covdata.setdefault(key, FileCoverage(key)).update(coverage)
  File "c:\users\public\programme\python\lib\site-packages\gcovr\coverage.py", line 372, in update
    self.line(lineno, noncode=True, excluded=False).update(line_cov)
  File "c:\users\public\programme\python\lib\site-packages\gcovr\coverage.py", line 288, in update
    self.decision.update(other.decision)
  File "c:\users\public\programme\python\lib\site-packages\gcovr\coverage.py", line 143, in update
    self.count_true += other.count_true
AttributeError: 'NoneType' object has no attribute 'count_true'
Traceback (most recent call last):
  File "c:\users\public\programme\python\lib\site-packages\gcovr\workers.py", line 77, in worker
    work(*args, **kwargs)
  File "c:\users\public\programme\python\lib\site-packages\gcovr\gcov.py", line 317, in process_datafile
    done = run_gcov_and_process_files(
  File "c:\users\public\programme\python\lib\site-packages\gcovr\gcov.py", line 490, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "c:\users\public\programme\python\lib\site-packages\gcovr\gcov.py", line 152, in process_gcov_data
    covdata.setdefault(key, FileCoverage(key)).update(coverage)
  File "c:\users\public\programme\python\lib\site-packages\gcovr\coverage.py", line 372, in update
    self.line(lineno, noncode=True, excluded=False).update(line_cov)
  File "c:\users\public\programme\python\lib\site-packages\gcovr\coverage.py", line 288, in update
    self.decision.update(other.decision)
  File "c:\users\public\programme\python\lib\site-packages\gcovr\coverage.py", line 143, in update
    self.count_true += other.count_true
AttributeError: 'NoneType' object has no attribute 'count_true'
(ERROR) Uncaught EXCEPTION
Traceback (most recent call last):
  File "c:\users\public\programme\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\public\programme\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Public\Programme\Python\Scripts\gcovr.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\users\public\programme\python\lib\site-packages\gcovr\__main__.py", line 308, in main
    collect_coverage_from_gcov(covdata, options)
  File "c:\users\public\programme\python\lib\site-packages\gcovr\__main__.py", line 367, in collect_coverage_from_gcov
    contexts = pool.wait()
  File "c:\users\public\programme\python\lib\site-packages\gcovr\workers.py", line 170, in __exit__
    self.wait()
  File "c:\users\public\programme\python\lib\site-packages\gcovr\workers.py", line 161, in wait
    raise self.exceptions[0][1]
  File "c:\users\public\programme\python\lib\site-packages\gcovr\__main__.py", line 367, in collect_coverage_from_gcov
    contexts = pool.wait()
  File "c:\users\public\programme\python\lib\site-packages\gcovr\workers.py", line 161, in wait
    raise self.exceptions[0][1]
  File "c:\users\public\programme\python\lib\site-packages\gcovr\workers.py", line 77, in worker
    work(*args, **kwargs)
  File "c:\users\public\programme\python\lib\site-packages\gcovr\gcov.py", line 317, in process_datafile
    done = run_gcov_and_process_files(
  File "c:\users\public\programme\python\lib\site-packages\gcovr\gcov.py", line 490, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "c:\users\public\programme\python\lib\site-packages\gcovr\gcov.py", line 152, in process_gcov_data
    covdata.setdefault(key, FileCoverage(key)).update(coverage)
  File "c:\users\public\programme\python\lib\site-packages\gcovr\coverage.py", line 372, in update
    self.line(lineno, noncode=True, excluded=False).update(line_cov)
  File "c:\users\public\programme\python\lib\site-packages\gcovr\coverage.py", line 288, in update
    self.decision.update(other.decision)
  File "c:\users\public\programme\python\lib\site-packages\gcovr\coverage.py", line 143, in update
    self.count_true += other.count_true
AttributeError: 'NoneType' object has no attribute 'count_true'

```

**To Reproduce**
Run gcovr with the following command:
`gcovr --gcov-ignore-parse-errors --exclude-unreachable-branches --exclude-throw-branches --gcov-executable C:/Users/Public/Programme/QNX/qos22/host/win64/x86_64/usr/bin/ntoaarch64-gcov-8.3.0.exe -r  THE_SOURCE_FOLDER --filter THE_SOURCE_FOLDER --json TEST_NAME.json`

**Expected behavior**
No exception.

**Desktop (please complete the following information):**
 - OS: Host: Windows 10, Target:  QNX OS for Safety 2.2
 - GCC version: gcc/qcc 8.3.0
 - GCOVR version 5.1

**Additional context**
- We use CMake
- We Compile on a Windows 10 system
- The tests run on an ARM QNX system
- We copy the *.gcda files from the TARGET and place them in compile folder.

I think this may be related to #637

**Comment by Spacetown** [comment]
Can you try to run with `--verbose` to get the gcov source file?

**Comment by simonCor** [comment]
Here is the output with verbose (one of the examples):
```
(DEBUG) Finding source file corresponding to a gcov data file
  currdir      C:\Users\Public\Programme\Jenkins\.jenkins\workspace\Testing\Unittest_Coverage\trace_files
  gcov_fname   C:\Users\Public\Programme\Jenkins\.jenkins\unique_folder\jenkins-Misc-Create_Virtual_Unique_Drive-1244\repo\CTCCPUexception.h##7344e3bbd9577364c98035fe036c2443.gcov
  source_fname C:\Users\Public\Programme\Jenkins\.jenkins\unique_folder\jenkins-Misc-Create_Virtual_Unique_Drive-1244\build\CTCCPUsoftware\HardwareAbstraction\APIWrapper\VacuAPI\SimVacu\UnitTest\CMakeFiles\tuSimVacu.dir\__\Object\src\SimVacu.cpp.gcno
  root         C:\Users\Public\Programme\Jenkins\.jenkins\unique_folder\jenkins-Misc-Create_Virtual_Unique_Drive-1244\repo
  fname        I:\repo\CTCCPUsoftware\Common\CTCCPUException\Object\inc\CTCCPUexception.h
(DEBUG) Parsing coverage data for file I:\repo\CTCCPUsoftware\Common\CTCCPUException\Object\inc\CTCCPUexception.h
(DEBUG) Starting the decision analysis
(DEBUG) Decision Analysis finished!
Traceback (most recent call last):
  File "c:\users\public\programme\python\lib\site-packages\gcovr\workers.py", line 77, in worker
    work(*args, **kwargs)
  File "c:\users\public\programme\python\lib\site-packages\gcovr\gcov.py", line 317, in process_datafile
    done = run_gcov_and_process_files(
  File "c:\users\public\programme\python\lib\site-packages\gcovr\gcov.py", line 490, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "c:\users\public\programme\python\lib\site-packages\gcovr\gcov.py", line 152, in process_gcov_data
    covdata.setdefault(key, FileCoverage(key)).update(coverage)
  File "c:\users\public\programme\python\lib\site-packages\gcovr\coverage.py", line 372, in update
    self.line(lineno, noncode=True, excluded=False).update(line_cov)
  File "c:\users\public\programme\python\lib\site-packages\gcovr\coverage.py", line 288, in update
    self.decision.update(other.decision)
  File "c:\users\public\programme\python\lib\site-packages\gcovr\coverage.py", line 143, in update
    self.count_true += other.count_true
AttributeError: 'NoneType' object has no attribute 'count_true'
Traceback (most recent call last):
  File "c:\users\public\programme\python\lib\site-packages\gcovr\workers.py", line 77, in worker
    work(*args, **kwargs)
  File "c:\users\public\programme\python\lib\site-packages\gcovr\gcov.py", line 317, in process_datafile
    done = run_gcov_and_process_files(
  File "c:\users\public\programme\python\lib\site-packages\gcovr\gcov.py", line 490, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "c:\users\public\programme\python\lib\site-packages\gcovr\gcov.py", line 152, in process_gcov_data
    covdata.setdefault(key, FileCoverage(key)).update(coverage)
  File "c:\users\public\programme\python\lib\site-packages\gcovr\coverage.py", line 372, in update
    self.line(lineno, noncode=True, excluded=False).update(line_cov)
  File "c:\users\public\programme\python\lib\site-packages\gcovr\coverage.py", line 288, in update
    self.decision.update(other.decision)
  File "c:\users\public\programme\python\lib\site-packages\gcovr\coverage.py", line 143, in update
    self.count_true += other.count_true
AttributeError: 'NoneType' object has no attribute 'count_true'
(ERROR) Uncaught EXCEPTION
Traceback (most recent call last):
  File "c:\users\public\programme\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\public\programme\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Public\Programme\Python\Scripts\gcovr.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\users\public\programme\python\lib\site-packages\gcovr\__main__.py", line 308, in main
    collect_coverage_from_gcov(covdata, options)
  File "c:\users\public\programme\python\lib\site-packages\gcovr\__main__.py", line 367, in collect_coverage_from_gcov
    contexts = pool.wait()
  File "c:\users\public\programme\python\lib\site-packages\gcovr\workers.py", line 170, in __exit__
    self.wait()
  File "c:\users\public\programme\python\lib\site-packages\gcovr\workers.py", line 161, in wait
    raise self.exceptions[0][1]
  File "c:\users\public\programme\python\lib\site-packages\gcovr\__main__.py", line 367, in collect_coverage_from_gcov
    contexts = pool.wait()
  File "c:\users\public\programme\python\lib\site-packages\gcovr\workers.py", line 161, in wait
    raise self.exceptions[0][1]
  File "c:\users\public\programme\python\lib\site-packages\gcovr\workers.py", line 77, in worker
    work(*args, **kwargs)
  File "c:\users\public\programme\python\lib\site-packages\gcovr\gcov.py", line 317, in process_datafile
    done = run_gcov_and_process_files(
  File "c:\users\public\programme\python\lib\site-packages\gcovr\gcov.py", line 490, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "c:\users\public\programme\python\lib\site-packages\gcovr\gcov.py", line 152, in process_gcov_data
    covdata.setdefault(key, FileCoverage(key)).update(coverage)
  File "c:\users\public\programme\python\lib\site-packages\gcovr\coverage.py", line 372, in update
    self.line(lineno, noncode=True, excluded=False).update(line_cov)
  File "c:\users\public\programme\python\lib\site-packages\gcovr\coverage.py", line 288, in update
    self.decision.update(other.decision)
  File "c:\users\public\programme\python\lib\site-packages\gcovr\coverage.py", line 143, in update
    self.count_true += other.count_true
AttributeError: 'NoneType' object has no attribute 'count_true'
```

Here is another example:
```
(DEBUG) Processing file: C:\Users\Public\Programme\Jenkins\.jenkins\unique_folder\jenkins-Misc-Create_Virtual_Unique_Drive-1244\build\CTCCPUsoftware\Application\Components\HOMe\Node\Object\CMakeFiles\aHOMeNode.dir\src\Node.cpp.gcda
(DEBUG) Running gcov: 'C:/Users/Public/Programme/QNX/qos22/host/win64/x86_64/usr/bin/ntoaarch64-gcov-8.3.0.exe C:\Users\Public\Programme\Jenkins\.jenkins\unique_folder\jenkins-Misc-Create_Virtual_Unique_Drive-1244\build\CTCCPUsoftware\Application\Components\HOMe\Node\Object\CMakeFiles\aHOMeNode.dir\src\Node.cpp.gcda --branch-counts --branch-probabilities --demangled-names --hash-filenames --object-directory C:\Users\Public\Programme\Jenkins\.jenkins\unique_folder\jenkins-Misc-Create_Virtual_Unique_Drive-1244\build\CTCCPUsoftware\Application\Components\HOMe\Node\Object\CMakeFiles\aHOMeNode.dir\src' in 'C:\Users\Public\Programme\Jenkins\.jenkins\unique_folder\jenkins-Misc-Create_Virtual_Unique_Drive-1244\repo'
(DEBUG) Finding source file corresponding to a gcov data file
  currdir      C:\Users\Public\Programme\Jenkins\.jenkins\workspace\Testing\Unittest_Coverage\trace_files
  gcov_fname   C:\Users\Public\Programme\Jenkins\.jenkins\unique_folder\jenkins-Misc-Create_Virtual_Unique_Drive-1244\repo\Node.cpp##b7a9bea1b532857a0025d9a78c7e5943.gcov
  source_fname C:\Users\Public\Programme\Jenkins\.jenkins\unique_folder\jenkins-Misc-Create_Virtual_Unique_Drive-1244\build\CTCCPUsoftware\Application\Components\HOMe\Node\Object\CMakeFiles\aHOMeNode.dir\src\Node.cpp.gcda
  root         C:\Users\Public\Programme\Jenkins\.jenkins\unique_folder\jenkins-Misc-Create_Virtual_Unique_Drive-1244\repo
  fname        I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp
(DEBUG) Parsing coverage data for file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp
(DEBUG) Excluding unreachable branch on line 42 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 42 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 42 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 42 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 42 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 42 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 42 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 42 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 42 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 42 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 44 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 44 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 49 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 49 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 69 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 72 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 73 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 75 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 76 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 80 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 81 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 82 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 82 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 82 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 94 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 100 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 101 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 107 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 112 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 112 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 114 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 115 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 117 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 118 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 120 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 121 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 127 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 128 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 130 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 133 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 134 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 190 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 205 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 208 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 210 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 217 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 218 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 243 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 244 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 245 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 247 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 250 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 252 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 252 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 445 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 445 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 453 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 453 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 454 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 458 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 459 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 460 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 461 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 468 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 468 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 468 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 478 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Excluding unreachable branch on line 508 in file I:\repo\CTCCPUsoftware\Application\Components\HOMe\Node\Object\src\Node.cpp: detected as exception-only code
(DEBUG) Starting the decision analysis
(DEBUG) Uncheckable decision at line 432
Traceback (most recent call last):
  File "c:\users\public\programme\python\lib\site-packages\gcovr\workers.py", line 77, in worker
    work(*args, **kwargs)
  File "c:\users\public\programme\python\lib\site-packages\gcovr\gcov.py", line 317, in process_datafile
    done = run_gcov_and_process_files(
  File "c:\users\public\programme\python\lib\site-packages\gcovr\gcov.py", line 490, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "c:\users\public\programme\python\lib\site-packages\gcovr\gcov.py", line 145, in process_gcov_data
    coverage = parse_coverage(
  File "c:\users\public\programme\python\lib\site-packages\gcovr\gcov_parser.py", line 368, in parse_coverage
    decision_parser.parse_all_lines()
  File "c:\users\public\programme\python\lib\site-packages\gcovr\decision_analysis.py", line 160, in parse_all_lines
    ).decision = DecisionCoverageConditional(
  File "c:\users\public\programme\python\lib\site-packages\gcovr\coverage.py", line 122, in __init__
    assert count_false >= 0
AssertionError
Traceback (most recent call last):
  File "c:\users\public\programme\python\lib\site-packages\gcovr\workers.py", line 77, in worker
    work(*args, **kwargs)
  File "c:\users\public\programme\python\lib\site-packages\gcovr\gcov.py", line 317, in process_datafile
    done = run_gcov_and_process_files(
  File "c:\users\public\programme\python\lib\site-packages\gcovr\gcov.py", line 490, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "c:\users\public\programme\python\lib\site-packages\gcovr\gcov.py", line 145, in process_gcov_data
    coverage = parse_coverage(
  File "c:\users\public\programme\python\lib\site-packages\gcovr\gcov_parser.py", line 368, in parse_coverage
    decision_parser.parse_all_lines()
  File "c:\users\public\programme\python\lib\site-packages\gcovr\decision_analysis.py", line 160, in parse_all_lines
    ).decision = DecisionCoverageConditional(
  File "c:\users\public\programme\python\lib\site-packages\gcovr\coverage.py", line 122, in __init__
    assert count_false >= 0
AssertionError
(ERROR) Uncaught EXCEPTION
Traceback (most recent call last):
  File "c:\users\public\programme\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\public\programme\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Public\Programme\Python\Scripts\gcovr.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\users\public\programme\python\lib\site-packages\gcovr\__main__.py", line 308, in main
    collect_coverage_from_gcov(covdata, options)
  File "c:\users\public\programme\python\lib\site-packages\gcovr\__main__.py", line 367, in collect_coverage_from_gcov
    contexts = pool.wait()
  File "c:\users\public\programme\python\lib\site-packages\gcovr\workers.py", line 170, in __exit__
    self.wait()
  File "c:\users\public\programme\python\lib\site-packages\gcovr\workers.py", line 161, in wait
    raise self.exceptions[0][1]
  File "c:\users\public\programme\python\lib\site-packages\gcovr\__main__.py", line 367, in collect_coverage_from_gcov
    contexts = pool.wait()
  File "c:\users\public\programme\python\lib\site-packages\gcovr\workers.py", line 161, in wait
    raise self.exceptions[0][1]
  File "c:\users\public\programme\python\lib\site-packages\gcovr\workers.py", line 77, in worker
    work(*args, **kwargs)
  File "c:\users\public\programme\python\lib\site-packages\gcovr\gcov.py", line 317, in process_datafile
    done = run_gcov_and_process_files(
  File "c:\users\public\programme\python\lib\site-packages\gcovr\gcov.py", line 490, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "c:\users\public\programme\python\lib\site-packages\gcovr\gcov.py", line 145, in process_gcov_data
    coverage = parse_coverage(
  File "c:\users\public\programme\python\lib\site-packages\gcovr\gcov_parser.py", line 368, in parse_coverage
    decision_parser.parse_all_lines()
  File "c:\users\public\programme\python\lib\site-packages\gcovr\decision_analysis.py", line 160, in parse_all_lines
    ).decision = DecisionCoverageConditional(
  File "c:\users\public\programme\python\lib\site-packages\gcovr\coverage.py", line 122, in __init__
    assert count_false >= 0
AssertionError
```

I see the exception often in the CTCCPUexception.h file. 

I will try to extract the gcov files - not so simple on the build server.

**Comment by Spacetown** [comment]
Can this be related to the problem fixed in open PR #617? Can you try the branch of the PR?

**Comment by klausweinbauer** [comment]
I ran into the same problem when using the --decisions flag.
Unfortunately, the PR did not fix this issue.

**Comment by simonCor** [comment]
Sorry for the late reply. I had the chance to test it and my problem is fixed in the current master.

Thank you!
