### ISSUE TITLE
simple1-drive-subst-html Fails integration tests for msys2 with gcc 13.1

### ISSUE THREAD

**Issue by ajpenner** [gcovr/gcovr#812]
**Describe the bug**
Some integration tests fail when using msys2 with gcc 13.1.

**To Reproduce**
1. clone the gcovr respository
2. in a cmd terminal run set CC=gcc-13
3. in the same cmd terminal run nox --session tests -- -k "html and not ninja"
4. Majority of tests pass but we get one failure:
gcovr/tests/test_gcovr.py::test_build[simple1-drive-subst-html] FAILED
With the following output
=============================================================================== FAILURES ================================================================================
_________________________________________________________________ test_build[simple1-drive-subst-html] __________________________________________________________________

compiled = 'simple1-drive-subst', format = 'html', available_targets = {'all': {'check-env'}, 'check-env': set(), 'clean': set(), 'cobertura': {'check-env'}, ...}
generate_reference = False, update_reference = False, archive_differences = False

    def test_build(
        compiled,
        format,
        available_targets,
        generate_reference,
        update_reference,
        archive_differences,
    ):
        name = compiled
        scrub = SCRUBBERS[format]
        output_pattern = OUTPUT_PATTERN[format]

        encoding = "utf8"
        if format == "html" and name.startswith("html-encoding-"):
            encoding = re.match("^html-encoding-(.*)$", name).group(1)

        os.chdir(os.path.join(basedir, name))
        assert run(["make", format])

        if generate_reference:  # pragma: no cover
            generate_reference_data(output_pattern)

        whole_diff_output = []
        for test_file, reference_file in find_reference_files(output_pattern):
            with open(test_file, encoding=encoding) as f:
                test_scrubbed = scrub(f.read())

            # Overwrite the file created above with the scrubbed content
            if generate_reference:  # pragma: no cover
                with open(reference_file, "w", encoding=encoding) as f:
                    f.write(test_scrubbed)
                reference_scrubbed = test_scrubbed
            else:
                with open(reference_file, encoding=encoding) as f:
                    reference_scrubbed = scrub(f.read())

            try:
                assert_equals(
                    reference_file,
                    reference_scrubbed,
                    test_file,
                    test_scrubbed,
                    encoding,
                )
            except AssertionError as e:  # pragma: no cover
                whole_diff_output += str(e) + "\n"
                if update_reference:
                    reference_file = update_reference_data(
                        reference_file, test_scrubbed, encoding
                    )
                if archive_differences:
                    archive_difference_data(name, test_file, reference_file)

            if generate_reference or update_reference:  # pragma: no cover
                remove_duplicate_data(
                    encoding, scrub, test_scrubbed, test_file, reference_file
                )

        diff_is_empty = len(whole_diff_output) == 0
>       assert diff_is_empty, "Diff output:\n" + "".join(whole_diff_output)
E       AssertionError: Diff output:
E         -- reference\gcc-8-Windows\coverage-details-linkcss.main.cpp.118fcbaaba162ba17933c7893247df3a.html
E         ++ coverage-details-linkcss.main.cpp.118fcbaaba162ba17933c7893247df3a.html
E           <html ...>
E             <head>
E             ...
E             </head>
E             <body>
E               <header>
E               ...
E               </header>
E               <nav>
E               ...
E               </nav>
E               <main>
E                 <div ...>
E                   <table>
E                     <tr>
E                     ...
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       </td>
E                       <td .../>
E                       <td ...>
E                         <span ...>
E                         ...
E                         </span>
E                         <span
E         -                 class="cpf"
E         +                 class="w"
E                         >
E         -                 <iostream>
E                         </span>
E                         <span
E         -                 class="cp"
E         +                 class="cpf"
E                         >
E         +                 <iostream>
E                         </span>
E         +               <span .../>
E                       </td>
E                     </tr>
E                     <tr ...>
E                     ...
E                     </tr>
E                     <tr ...>
E                     ...
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       </td>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                         <span ...>
E                         ...
E                         </span>
E                         <span
E         -                 class="nf"
E         +                 class="w"
E                         >
E         -                 foo
E                         </span>
E                         <span
E         -                 class="p"
E         +                 class="nf"
E                         >
E         -                 (
E         +                 foo
E                         </span>
E                         <span
E         -                 class="kt"
E         +                 class="p"
E                         >
E         -                 int
E         +                 (
E                         </span>
E                         <span
E         -                 class="n"
E         +                 class="kt"
E                         >
E         -                 param
E         +                 int
E                         </span>
E                         <span
E         -                 class="p"
E         +                 class="w"
E                         >
E         -                 )
E                         </span>
E                         <span
E         -                 class="p"
E         +                 class="n"
E                         >
E         -                 {
E         +                 param
E                         </span>
E         +               <span ...>...</span>
E         +               <span ...>...</span>
E         +               <span ...>...</span>
E         +               <span .../>
E                       </td>
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                         <span
E         -                 class="k"
E         +                 class="w"
E                         >
E         -                 if
E                         </span>
E                         <span
E         -                 class="p"
E         +                 class="k"
E                         >
E         -                 (
E         +                 if
E                         </span>
E                         <span
E         -                 class="n"
E         +                 class="w"
E                         >
E         -                 param
E                         </span>
E                         <span ...>
E         -                 )
E         +                 (
E                         </span>
E                         <span
E         -                 class="p"
E         +                 class="n"
E                         >
E         -                 {
E         +                 param
E                         </span>
E         +               <span ...>...</span>
E         +               <span ...>...</span>
E         +               <span ...>...</span>
E         +               <span .../>
E                       </td>
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       </td>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                         <span
E         -                 class="k"
E         +                 class="w"
E                         >
E         -                 return
E                         </span>
E                         <span
E         -                 class="mi"
E         +                 class="k"
E                         >
E         -                 1
E         +                 return
E                         </span>
E                         <span
E         -                 class="p"
E         +                 class="w"
E                         >
E         -                 ;
E                         </span>
E                         <span
E         -                 class="c1"
E         +                 class="mi"
E                         >
E         -                 //std::cout << "param not null." << std::endl;
E         +                 1
E                         </span>
E         +               <span ...>...</span>
E         +               <span ...>...</span>
E         +               <span ...>...</span>
E                       </td>
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       </td>
E                       <td .../>
E                       <td ...>
E                         <span
E         -                 class="p"
E         +                 class="w"
E                         >
E         -                 }
E                         </span>
E                         <span
E         -                 class="k"
E         +                 class="p"
E                         >
E         -                 else
E         +                 }
E                         </span>
E                         <span
E         -                 class="p"
E         +                 class="w"
E                         >
E         -                 {
E                         </span>
E         +               <span ...>...</span>
E         +               <span ...>...</span>
E         +               <span ...>...</span>
E         +               <span .../>
E                       </td>
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       </td>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                         <span
E         -                 class="k"
E         +                 class="w"
E                         >
E         -                 return
E                         </span>
E                         <span
E         -                 class="mi"
E         +                 class="k"
E                         >
E         -                 0
E         +                 return
E                         </span>
E                         <span
E         -                 class="p"
E         +                 class="w"
E                         >
E         -                 ;
E                         </span>
E                         <span
E         -                 class="c1"
E         +                 class="mi"
E                         >
E         -                 //std::cout << "param is null." << std::endl;
E         +                 0
E                         </span>
E         +               <span ...>...</span>
E         +               <span ...>...</span>
E         +               <span ...>...</span>
E                       </td>
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       </td>
E                       <td .../>
E                       <td ...>
E                         <span
E         -                 class="p"
E         +                 class="w"
E                         >
E         -                 }
E                         </span>
E         +               <span ...>...</span>
E         +               <span .../>
E                       </td>
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       </td>
E                       <td .../>
E                       <td ...>
E                         <span ...>
E                         ...
E                         </span>
E         +               <span .../>
E                       </td>
E                     </tr>
E                     <tr ...>
E                     ...
E                     </tr>
E                     <tr ...>
E                     ...
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       </td>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                         <span ...>
E                         ...
E                         </span>
E                         <span
E         -                 class="nf"
E         +                 class="w"
E                         >
E         -                 main
E                         </span>
E                         <span
E         -                 class="p"
E         +                 class="nf"
E                         >
E         -                 (
E         +                 main
E                         </span>
E                         <span
E         -                 class="kt"
E         +                 class="p"
E                         >
E         -                 int
E         +                 (
E                         </span>
E                         <span
E         -                 class="n"
E         +                 class="kt"
E                         >
E         -                 argc
E         +                 int
E                         </span>
E                         <span
E         -                 class="p"
E         +                 class="w"
E                         >
E         -                 ,
E                         </span>
E                         <span
E         -                 class="kt"
E         +                 class="n"
E                         >
E         -                 char
E         +                 argc
E                         </span>
E                         <span
E         -                 class="o"
E         +                 class="p"
E                         >
E         -                 *
E         +                 ,
E                         </span>
E                         <span
E         -                 class="n"
E         +                 class="w"
E                         >
E         -                 argv
E                         </span>
E                         <span
E         -                 class="p"
E         +                 class="kt"
E                         >
E         -                 [])
E         +                 char
E                         </span>
E                         <span
E         -                 class="p"
E         +                 class="o"
E                         >
E         -                 {
E         +                 *
E                         </span>
E         +               <span ...>...</span>
E         +               <span ...>...</span>
E         +               <span ...>...</span>
E         +               <span ...>...</span>
E         +               <span ...>...</span>
E         +               <span .../>
E                       </td>
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       </td>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                         <span
E         -                 class="n"
E         +                 class="w"
E                         >
E         -                 foo
E                         </span>
E                         <span
E         -                 class="p"
E         +                 class="n"
E                         >
E         -                 (
E         +                 foo
E                         </span>
E         +               <span ...>...</span>
E         +               <span .../>
E                       </td>
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       </td>
E                       <td .../>
E                       <td ...>
E                         <span
E         -                 class="mi"
E         +                 class="w"
E                         >
E         -                 0
E                         </span>
E         +               <span ...>...</span>
E         +               <span .../>
E                       </td>
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       </td>
E                       <td .../>
E                       <td ...>
E                         <span
E         -                 class="p"
E         +                 class="w"
E                         >
E         -                 )
E                         </span>
E         +               <span ...>...</span>
E         +               <span .../>
E                       </td>
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       </td>
E                       <td .../>
E                       <td ...>
E                         <span
E         -                 class="p"
E         +                 class="w"
E                         >
E         -                 ;
E                         </span>
E         +               <span ...>...</span>
E         +               <span .../>
E                       </td>
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                         <span
E         -                 class="k"
E         +                 class="w"
E                         >
E         -                 if
E                         </span>
E                         <span
E         -                 class="p"
E         +                 class="k"
E                         >
E         -                 (
E         +                 if
E                         </span>
E                         <span
E         -                 class="n"
E         +                 class="w"
E                         >
E         -                 argc
E                         </span>
E                         <span
E         -                 class="o"
E         +                 class="p"
E                         >
E         -                 >
E         +                 (
E                         </span>
E                         <span
E         -                 class="mi"
E         +                 class="n"
E                         >
E         -                 1
E         +                 argc
E                         </span>
E                         <span
E         -                 class="p"
E         +                 class="w"
E                         >
E         -                 )
E                         </span>
E                         <span
E         -                 class="p"
E         +                 class="o"
E                         >
E         -                 {
E         +                 >
E                         </span>
E         +               <span ...>...</span>
E         +               <span ...>...</span>
E         +               <span ...>...</span>
E         +               <span ...>...</span>
E         +               <span ...>...</span>
E         +               <span .../>
E                       </td>
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       </td>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                         <span
E         -                 class="n"
E         +                 class="w"
E                         >
E         -                 foo
E                         </span>
E                         <span
E         -                 class="p"
E         +                 class="n"
E                         >
E         -                 (
E         +                 foo
E                         </span>
E         +               <span ...>...</span>
E         +               <span .../>
E                       </td>
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       </td>
E                       <td .../>
E                       <td ...>
E                         <span
E         -                 class="mi"
E         +                 class="w"
E                         >
E         -                 1
E                         </span>
E         +               <span ...>...</span>
E         +               <span .../>
E                       </td>
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       </td>
E                       <td .../>
E                       <td ...>
E                         <span
E         -                 class="p"
E         +                 class="w"
E                         >
E         -                 )
E                         </span>
E         +               <span ...>...</span>
E         +               <span .../>
E                       </td>
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       </td>
E                       <td .../>
E                       <td ...>
E                         <span
E         -                 class="p"
E         +                 class="w"
E                         >
E         -                 ;
E                         </span>
E         +               <span ...>...</span>
E         +               <span .../>
E                       </td>
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       </td>
E                       <td .../>
E                       <td ...>
E                         <span
E         -                 class="p"
E         +                 class="w"
E                         >
E         -                 }
E                         </span>
E         +               <span ...>...</span>
E         +               <span .../>
E                       </td>
E                     </tr>
E                     <tr ...>
E                     ...
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       </td>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                         <span
E         -                 class="k"
E         +                 class="w"
E                         >
E         -                 return
E                         </span>
E                         <span
E         -                 class="mi"
E         +                 class="k"
E                         >
E         -                 0
E         +                 return
E                         </span>
E                         <span
E         -                 class="p"
E         +                 class="w"
E                         >
E         -                 ;
E                         </span>
E         +               <span ...>...</span>
E         +               <span ...>...</span>
E         +               <span .../>
E                       </td>
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       </td>
E                       <td .../>
E                       <td ...>
E                         <span ...>
E                         ...
E                         </span>
E         +               <span .../>
E                       </td>
E                     </tr>
E                     <tr ...>
E                     ...
E                     </tr>
E                   </table>
E                 </div>
E                 <hr/>
E               </main>
E               <footer>
E               ...
E               </footer>
E             </body>
E           </html>
E
E       assert False

C:\dev\GitRepos\gcovr\gcovr\tests\test_gcovr.py:527: AssertionError
------------------------------------------------------------------------- Captured stdout setup -------------------------------------------------------------------------
STDOUT - START ['make', 'clean']
rm -f testcase
rm -f *.gc*
rm -f coverage.* coverage_details*.* cobertura.xml sonarqube.xml summary_coverage.json coveralls.json
rm -rf output
STDOUT - END
STDOUT - START ['make', 'clean']
rm -f testcase
rm -f fail_under.stderr
rm -f *.gc*
rm -f coverage.txt coverage*.html coverage*.css cobertura.xml sonarqube.xml coverage.json summary_coverage.json coveralls.json
STDOUT - END
STDOUT - START ['make', 'all']
Using drive Z:.
cmd.exe /C "subst Z: .."; ( pushd Z:/simple1-drive-subst &&  C:/msys64/mingw32/bin/g++.EXE -fprofile-arcs -ftest-coverage -fPIC main.cpp -o testcase ) || ( popd & cmd.exe /C "subst Z: /d" & exit 1 ); cmd.exe /C "subst Z: /d"
/z/simple1-drive-subst /c/dev/GitRepos/gcovr/gcovr/tests/simple1-drive-subst
STDOUT - END
------------------------------------------------------------------------- Captured stdout call --------------------------------------------------------------------------
STDOUT - START ['make', 'html']
Using drive Z:.
cmd.exe /C "subst Z: .."; ( pushd Z:/simple1-drive-subst &&  ./testcase ) || ( popd & cmd.exe /C "subst Z: /d" & exit 1 ); cmd.exe /C "subst Z: /d"
/z/simple1-drive-subst /c/dev/GitRepos/gcovr/gcovr/tests/simple1-drive-subst
# these test cases also cover some CSS-linking permutations
cmd.exe /C "subst Z: .."; ( pushd Z:/simple1-drive-subst &&  C:/dev/GitRepos/gcovr/.nox/tests_compiler-gcc-13/Scripts/python.EXE -m gcovr --verbose -d --html-details coverage-details-linkcss.html ) || ( popd & cmd.exe /C "subst Z: /d" & exit 1 ); cmd.exe /C "subst Z: /d"
/z/simple1-drive-subst /c/dev/GitRepos/gcovr/gcovr/tests/simple1-drive-subst
(DEBUG) File system is case insensitive.
(DEBUG) Filters for --root: (1)
(DEBUG)  - re.compile('^C:\\\\dev\\\\GitRepos\\\\gcovr\\\\gcovr\\\\tests\\\\simple1\\-drive\\-subst\\\\')
(DEBUG) Filters for --filter: (1)
(DEBUG)  - DirectoryPrefixFilter(C:/dev/GitRepos/gcovr/gcovr/tests/simple1\-drive\-subst/)
(DEBUG) Filters for --exclude: (0)
(DEBUG) Filters for --gcov-filter: (1)
(DEBUG)  - AlwaysMatchFilter()
(DEBUG) Filters for --gcov-exclude: (0)
(DEBUG) Filters for --gcov-exclude-directories: (0)
(DEBUG) Scanning directory . for gcda/gcno files...
(DEBUG) Found 2 files (and will process 1)
(DEBUG) Pool started with 1 threads
(DEBUG) Processing file: C:\dev\GitRepos\gcovr\gcovr\tests\simple1-drive-subst\testcase-main.gcda
(DEBUG) Running gcov: 'C:/msys64/mingw32/bin/gcov.EXE --help' in '.'
(DEBUG) Running gcov: 'C:/msys64/mingw32/bin/gcov.EXE --help-hidden' in '.'
(DEBUG) Running gcov: 'C:/msys64/mingw32/bin/gcov.EXE C:/dev/GitRepos/gcovr/gcovr/tests/simple1-drive-subst/testcase-main.gcda --branch-counts --branch-probabilities --all-blocks --demangled-names --hash-filenames --object-directory C:/dev/GitRepos/gcovr/gcovr/tests/simple1-drive-subst' in 'C:\dev\GitRepos\gcovr\gcovr\tests\simple1-drive-subst'
(DEBUG) Finding source file corresponding to a gcov data file
  gcov_fname   C:\dev\GitRepos\gcovr\gcovr\tests\simple1-drive-subst\main.cpp##118fcbaaba162ba17933c7893247df3a.gcov
  current_dir      C:\dev\GitRepos\gcovr\gcovr\tests\simple1-drive-subst
  root         C:\dev\GitRepos\gcovr\gcovr\tests\simple1-drive-subst
  starting_dir C:\dev\GitRepos\gcovr\gcovr\tests\simple1-drive-subst
  obj_dir      None
  gcda_fname   C:/dev/GitRepos/gcovr/gcovr/tests/simple1-drive-subst/testcase-main.gcda
  --> fname    C:/dev/GitRepos/gcovr/gcovr/tests/simple1-drive-subst/main.cpp
(DEBUG) Parsing coverage data for file C:/dev/GitRepos/gcovr/gcovr/tests/simple1-drive-subst/main.cpp
STDOUT - END
======================================================================== short test summary info ========================================================================
FAILED gcovr/tests/test_gcovr.py::test_build[simple1-drive-subst-html] - AssertionError: Diff output:
======================================= 1 failed, 98 passed, 4 skipped, 339 deselected, 1 xfailed, 1 xpassed in 503.50s (0:08:23) =======================================
nox > Command python -m pytest -k 'html and not ninja' -- doc gcovr failed with exit code 1
nox > Session tests_compiler(gcc-13) failed.
nox > Ran multiple sessions:
nox > * tests: success
nox > * tests_compiler(gcc-13): failed

**Expected behavior**
I would expect the integration tests to pass using msys2 and gcc 13.1

**Desktop (please complete the following information):**
 - OS: Windows
 - GCC version: gcc.exe (Rev7, Built by MSYS2 project) 13.1.0
 - GCOVR version: master
 - Project directory layout:
 -     Cloned from repository

**Comment by Spacetown** [comment]
In the CI this test is also failing and I try since one week to fix this. 😄

**Comment by Spacetown** [comment]
Now the CI is fixed. Please can you try again?

**Comment by ajpenner** [comment]
Unfortunately, no luck, it is still failing:

______________________________________________________________________________________ test_build[simple1-drive-subst-html] ______________________________________________________________________________________

compiled = 'simple1-drive-subst', format = 'html', available_targets = {'all': {'check-env'}, 'check-env': set(), 'clean': set(), 'cobertura': {'check-env'}, ...}, generate_reference = False
update_reference = False, archive_differences = False

    def test_build(
        compiled,
        format,
        available_targets,
        generate_reference,
        update_reference,
        archive_differences,
    ):
        name = compiled
        scrub = SCRUBBERS[format]
        output_pattern = OUTPUT_PATTERN[format]

        encoding = "utf8"
        if format == "html" and name.startswith("html-encoding-"):
            encoding = re.match("^html-encoding-(.*)$", name).group(1)

        os.chdir(os.path.join(basedir, name))
        assert run(["make", format])

        if generate_reference:  # pragma: no cover
            generate_reference_data(output_pattern)

        whole_diff_output = []
        for test_file, reference_file in find_reference_files(output_pattern):
            with open(test_file, encoding=encoding) as f:
                test_scrubbed = scrub(f.read())

            # Overwrite the file created above with the scrubbed content
            if generate_reference:  # pragma: no cover
                with open(reference_file, "w", encoding=encoding) as f:
                    f.write(test_scrubbed)
                reference_scrubbed = test_scrubbed
            else:
                with open(reference_file, encoding=encoding) as f:
                    reference_scrubbed = scrub(f.read())

            try:
                assert_equals(
                    reference_file,
                    reference_scrubbed,
                    test_file,
                    test_scrubbed,
                    encoding,
                )
            except AssertionError as e:  # pragma: no cover
                whole_diff_output += str(e) + "\n"
                if update_reference:
                    reference_file = update_reference_data(
                        reference_file, test_scrubbed, encoding
                    )
                if archive_differences:
                    archive_difference_data(name, test_file, reference_file)

            if generate_reference or update_reference:  # pragma: no cover
                remove_duplicate_data(
                    encoding, scrub, test_scrubbed, test_file, reference_file
                )

        diff_is_empty = len(whole_diff_output) == 0
>       assert diff_is_empty, "Diff output:\n" + "".join(whole_diff_output)
E       AssertionError: Diff output:
E         -- reference\gcc-8-Windows\coverage-details-linkcss.main.cpp.118fcbaaba162ba17933c7893247df3a.html
E         ++ coverage-details-linkcss.main.cpp.118fcbaaba162ba17933c7893247df3a.html
E           <html ...>
E             <head>
E             ...
E             </head>
E             <body>
E               <header>
E               ...
E               </header>
E               <nav>
E               ...
E               </nav>
E               <main>
E                 <div ...>
E                   <table>
E                     <tr>
E                     ...
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       </td>
E                       <td .../>
E                       <td ...>
E                         <span ...>
E                         ...
E                         </span>
E                         <span
E         -                 class="cpf"
E         +                 class="w"
E                         >
E         -                 <iostream>
E                         </span>
E                         <span
E         -                 class="cp"
E         +                 class="cpf"
E                         >
E         +                 <iostream>
E                         </span>
E         +               <span .../>
E                       </td>
E                     </tr>
E                     <tr ...>
E                     ...
E                     </tr>
E                     <tr ...>
E                     ...
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       </td>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                         <span ...>
E                         ...
E                         </span>
E                         <span
E         -                 class="nf"
E         +                 class="w"
E                         >
E         -                 foo
E                         </span>
E                         <span
E         -                 class="p"
E         +                 class="nf"
E                         >
E         -                 (
E         +                 foo
E                         </span>
E                         <span
E         -                 class="kt"
E         +                 class="p"
E                         >
E         -                 int
E         +                 (
E                         </span>
E                         <span
E         -                 class="n"
E         +                 class="kt"
E                         >
E         -                 param
E         +                 int
E                         </span>
E                         <span
E         -                 class="p"
E         +                 class="w"
E                         >
E         -                 )
E                         </span>
E                         <span
E         -                 class="p"
E         +                 class="n"
E                         >
E         -                 {
E         +                 param
E                         </span>
E         +               <span ...>...</span>
E         +               <span ...>...</span>
E         +               <span ...>...</span>
E         +               <span .../>
E                       </td>
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                         <span
E         -                 class="k"
E         +                 class="w"
E                         >
E         -                 if
E                         </span>
E                         <span
E         -                 class="p"
E         +                 class="k"
E                         >
E         -                 (
E         +                 if
E                         </span>
E                         <span
E         -                 class="n"
E         +                 class="w"
E                         >
E         -                 param
E                         </span>
E                         <span ...>
E         -                 )
E         +                 (
E                         </span>
E                         <span
E         -                 class="p"
E         +                 class="n"
E                         >
E         -                 {
E         +                 param
E                         </span>
E         +               <span ...>...</span>
E         +               <span ...>...</span>
E         +               <span ...>...</span>
E         +               <span .../>
E                       </td>
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       </td>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                         <span
E         -                 class="k"
E         +                 class="w"
E                         >
E         -                 return
E                         </span>
E                         <span
E         -                 class="mi"
E         +                 class="k"
E                         >
E         -                 1
E         +                 return
E                         </span>
E                         <span
E         -                 class="p"
E         +                 class="w"
E                         >
E         -                 ;
E                         </span>
E                         <span
E         -                 class="c1"
E         +                 class="mi"
E                         >
E         -                 //std::cout << "param not null." << std::endl;
E         +                 1
E                         </span>
E         +               <span ...>...</span>
E         +               <span ...>...</span>
E         +               <span ...>...</span>
E                       </td>
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       </td>
E                       <td .../>
E                       <td ...>
E                         <span
E         -                 class="p"
E         +                 class="w"
E                         >
E         -                 }
E                         </span>
E                         <span
E         -                 class="k"
E         +                 class="p"
E                         >
E         -                 else
E         +                 }
E                         </span>
E                         <span
E         -                 class="p"
E         +                 class="w"
E                         >
E         -                 {
E                         </span>
E         +               <span ...>...</span>
E         +               <span ...>...</span>
E         +               <span ...>...</span>
E         +               <span .../>
E                       </td>
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       </td>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                         <span
E         -                 class="k"
E         +                 class="w"
E                         >
E         -                 return
E                         </span>
E                         <span
E         -                 class="mi"
E         +                 class="k"
E                         >
E         -                 0
E         +                 return
E                         </span>
E                         <span
E         -                 class="p"
E         +                 class="w"
E                         >
E         -                 ;
E                         </span>
E                         <span
E         -                 class="c1"
E         +                 class="mi"
E                         >
E         -                 //std::cout << "param is null." << std::endl;
E         +                 0
E                         </span>
E         +               <span ...>...</span>
E         +               <span ...>...</span>
E         +               <span ...>...</span>
E                       </td>
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       </td>
E                       <td .../>
E                       <td ...>
E                         <span
E         -                 class="p"
E         +                 class="w"
E                         >
E         -                 }
E                         </span>
E         +               <span ...>...</span>
E         +               <span .../>
E                       </td>
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       </td>
E                       <td .../>
E                       <td ...>
E                         <span ...>
E                         ...
E                         </span>
E         +               <span .../>
E                       </td>
E                     </tr>
E                     <tr ...>
E                     ...
E                     </tr>
E                     <tr ...>
E                     ...
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       </td>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                         <span ...>
E                         ...
E                         </span>
E                         <span
E         -                 class="nf"
E         +                 class="w"
E                         >
E         -                 main
E                         </span>
E                         <span
E         -                 class="p"
E         +                 class="nf"
E                         >
E         -                 (
E         +                 main
E                         </span>
E                         <span
E         -                 class="kt"
E         +                 class="p"
E                         >
E         -                 int
E         +                 (
E                         </span>
E                         <span
E         -                 class="n"
E         +                 class="kt"
E                         >
E         -                 argc
E         +                 int
E                         </span>
E                         <span
E         -                 class="p"
E         +                 class="w"
E                         >
E         -                 ,
E                         </span>
E                         <span
E         -                 class="kt"
E         +                 class="n"
E                         >
E         -                 char
E         +                 argc
E                         </span>
E                         <span
E         -                 class="o"
E         +                 class="p"
E                         >
E         -                 *
E         +                 ,
E                         </span>
E                         <span
E         -                 class="n"
E         +                 class="w"
E                         >
E         -                 argv
E                         </span>
E                         <span
E         -                 class="p"
E         +                 class="kt"
E                         >
E         -                 [])
E         +                 char
E                         </span>
E                         <span
E         -                 class="p"
E         +                 class="o"
E                         >
E         -                 {
E         +                 *
E                         </span>
E         +               <span ...>...</span>
E         +               <span ...>...</span>
E         +               <span ...>...</span>
E         +               <span ...>...</span>
E         +               <span ...>...</span>
E         +               <span .../>
E                       </td>
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       </td>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                         <span
E         -                 class="n"
E         +                 class="w"
E                         >
E         -                 foo
E                         </span>
E                         <span
E         -                 class="p"
E         +                 class="n"
E                         >
E         -                 (
E         +                 foo
E                         </span>
E         +               <span ...>...</span>
E         +               <span .../>
E                       </td>
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       </td>
E                       <td .../>
E                       <td ...>
E                         <span
E         -                 class="mi"
E         +                 class="w"
E                         >
E         -                 0
E                         </span>
E         +               <span ...>...</span>
E         +               <span .../>
E                       </td>
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       </td>
E                       <td .../>
E                       <td ...>
E                         <span
E         -                 class="p"
E         +                 class="w"
E                         >
E         -                 )
E                         </span>
E         +               <span ...>...</span>
E         +               <span .../>
E                       </td>
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       </td>
E                       <td .../>
E                       <td ...>
E                         <span
E         -                 class="p"
E         +                 class="w"
E                         >
E         -                 ;
E                         </span>
E         +               <span ...>...</span>
E         +               <span .../>
E                       </td>
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                         <span
E         -                 class="k"
E         +                 class="w"
E                         >
E         -                 if
E                         </span>
E                         <span
E         -                 class="p"
E         +                 class="k"
E                         >
E         -                 (
E         +                 if
E                         </span>
E                         <span
E         -                 class="n"
E         +                 class="w"
E                         >
E         -                 argc
E                         </span>
E                         <span
E         -                 class="o"
E         +                 class="p"
E                         >
E         -                 >
E         +                 (
E                         </span>
E                         <span
E         -                 class="mi"
E         +                 class="n"
E                         >
E         -                 1
E         +                 argc
E                         </span>
E                         <span
E         -                 class="p"
E         +                 class="w"
E                         >
E         -                 )
E                         </span>
E                         <span
E         -                 class="p"
E         +                 class="o"
E                         >
E         -                 {
E         +                 >
E                         </span>
E         +               <span ...>...</span>
E         +               <span ...>...</span>
E         +               <span ...>...</span>
E         +               <span ...>...</span>
E         +               <span ...>...</span>
E         +               <span .../>
E                       </td>
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       </td>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                         <span
E         -                 class="n"
E         +                 class="w"
E                         >
E         -                 foo
E                         </span>
E                         <span
E         -                 class="p"
E         +                 class="n"
E                         >
E         -                 (
E         +                 foo
E                         </span>
E         +               <span ...>...</span>
E         +               <span .../>
E                       </td>
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       </td>
E                       <td .../>
E                       <td ...>
E                         <span
E         -                 class="mi"
E         +                 class="w"
E                         >
E         -                 1
E                         </span>
E         +               <span ...>...</span>
E         +               <span .../>
E                       </td>
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       </td>
E                       <td .../>
E                       <td ...>
E                         <span
E         -                 class="p"
E         +                 class="w"
E                         >
E         -                 )
E                         </span>
E         +               <span ...>...</span>
E         +               <span .../>
E                       </td>
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       </td>
E                       <td .../>
E                       <td ...>
E                         <span
E         -                 class="p"
E         +                 class="w"
E                         >
E         -                 ;
E                         </span>
E         +               <span ...>...</span>
E         +               <span .../>
E                       </td>
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       </td>
E                       <td .../>
E                       <td ...>
E                         <span
E         -                 class="p"
E         +                 class="w"
E                         >
E         -                 }
E                         </span>
E         +               <span ...>...</span>
E         +               <span .../>
E                       </td>
E                     </tr>
E                     <tr ...>
E                     ...
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       </td>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                         <span
E         -                 class="k"
E         +                 class="w"
E                         >
E         -                 return
E                         </span>
E                         <span
E         -                 class="mi"
E         +                 class="k"
E                         >
E         -                 0
E         +                 return
E                         </span>
E                         <span
E         -                 class="p"
E         +                 class="w"
E                         >
E         -                 ;
E                         </span>
E         +               <span ...>...</span>
E         +               <span ...>...</span>
E         +               <span .../>
E                       </td>
E                     </tr>
E                     <tr ...>
E                       <td ...>
E                       ...
E                       </td>
E                       <td ...>
E                       </td>
E                       <td .../>
E                       <td ...>
E                         <span ...>
E                         ...
E                         </span>
E         +               <span .../>
E                       </td>
E                     </tr>
E                     <tr ...>
E                     ...
E                     </tr>
E                   </table>
E                 </div>
E                 <hr/>
E               </main>
E               <footer>
E               ...
E               </footer>
E             </body>
E           </html>
E
E       assert False

C:\dev\GitRepos\gcovr\gcovr\tests\test_gcovr.py:527: AssertionError
--------------------------------------------------------------------------------------------- Captured stdout setup ----------------------------------------------------------------------------------------------
STDOUT - START ['make', 'clean']
rm -f testcase
rm -f *.gc*
rm -f coverage.* coverage_details*.* cobertura.xml sonarqube.xml summary_coverage.json coveralls.json
rm -rf output
STDOUT - END
STDOUT - START ['make', 'clean']
rm -f testcase
rm -f fail_under.stderr
rm -f *.gc*
rm -f coverage.txt coverage*.html coverage*.css cobertura.xml sonarqube.xml coverage.json summary_coverage.json coveralls.json
STDOUT - END
STDOUT - START ['make', 'all']
Using drive Z:.
cmd.exe /C "subst Z: .."; ( pushd Z:/simple1-drive-subst &&  C:/msys64/mingw32/bin/g++.EXE -fprofile-arcs -ftest-coverage -fPIC main.cpp -o testcase ) || ( popd & cmd.exe /C "subst Z: /d" & exit 1 ); cmd.exe /C "subst Z: /d"
/z/simple1-drive-subst /c/dev/GitRepos/gcovr/gcovr/tests/simple1-drive-subst
STDOUT - END
---------------------------------------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------------------------------------
STDOUT - START ['make', 'html']
Using drive Z:.
cmd.exe /C "subst Z: .."; ( pushd Z:/simple1-drive-subst &&  ./testcase ) || ( popd & cmd.exe /C "subst Z: /d" & exit 1 ); cmd.exe /C "subst Z: /d"
/z/simple1-drive-subst /c/dev/GitRepos/gcovr/gcovr/tests/simple1-drive-subst
# these test cases also cover some CSS-linking permutations
cmd.exe /C "subst Z: .."; ( pushd Z:/simple1-drive-subst &&  C:/dev/GitRepos/gcovr/.nox/tests_compiler-gcc-13/Scripts/python.EXE -m gcovr --verbose -d --html-details coverage-details-linkcss.html ) || ( popd & cmd.exe /C "subst Z: /d" & exit 1 ); cmd.exe /C "subst Z: /d"
/z/simple1-drive-subst /c/dev/GitRepos/gcovr/gcovr/tests/simple1-drive-subst
(DEBUG) File system is case insensitive.
(DEBUG) Filters for --root: (1)
(DEBUG)  - re.compile('^C:\\\\dev\\\\GitRepos\\\\gcovr\\\\gcovr\\\\tests\\\\simple1\\-drive\\-subst\\\\')
(DEBUG) Filters for --filter: (1)
(DEBUG)  - DirectoryPrefixFilter(C:/dev/GitRepos/gcovr/gcovr/tests/simple1\-drive\-subst/)
(DEBUG) Filters for --exclude: (0)
(DEBUG) Filters for --gcov-filter: (1)
(DEBUG)  - AlwaysMatchFilter()
(DEBUG) Filters for --gcov-exclude: (0)
(DEBUG) Filters for --gcov-exclude-directories: (0)
(DEBUG) Scanning directory . for gcda/gcno files...
(DEBUG) Found 2 files (and will process 1)
(DEBUG) Pool started with 1 threads
(DEBUG) Processing file: C:\dev\GitRepos\gcovr\gcovr\tests\simple1-drive-subst\testcase-main.gcda
(DEBUG) Running gcov: 'C:/msys64/mingw32/bin/gcov.EXE --help' in '.'
(DEBUG) Running gcov: 'C:/msys64/mingw32/bin/gcov.EXE --help-hidden' in '.'
(DEBUG) Running gcov: 'C:/msys64/mingw32/bin/gcov.EXE C:/dev/GitRepos/gcovr/gcovr/tests/simple1-drive-subst/testcase-main.gcda --branch-counts --branch-probabilities --all-blocks --demangled-names --hash-filenames --object-directory C:/dev/GitRepos/gcovr/gcovr/tests/simple1-drive-subst' in 'C:\dev\GitRepos\gcovr\gcovr\tests\simple1-drive-subst'
(DEBUG) Finding source file corresponding to a gcov data file
  gcov_fname   C:\dev\GitRepos\gcovr\gcovr\tests\simple1-drive-subst\main.cpp##118fcbaaba162ba17933c7893247df3a.gcov
  current_dir      C:\dev\GitRepos\gcovr\gcovr\tests\simple1-drive-subst
  root         C:\dev\GitRepos\gcovr\gcovr\tests\simple1-drive-subst
  starting_dir C:\dev\GitRepos\gcovr\gcovr\tests\simple1-drive-subst
  obj_dir      None
  gcda_fname   C:/dev/GitRepos/gcovr/gcovr/tests/simple1-drive-subst/testcase-main.gcda
  --> fname    C:/dev/GitRepos/gcovr/gcovr/tests/simple1-drive-subst/main.cpp
(DEBUG) Parsing coverage data for file C:/dev/GitRepos/gcovr/gcovr/tests/simple1-drive-subst/main.cpp
STDOUT - END
============================================================================================ short test summary info =============================================================================================
FAILED gcovr/tests/test_gcovr.py::test_build[simple1-drive-subst-html] - AssertionError: Diff output:
=========================================================== 1 failed, 98 passed, 4 skipped, 339 deselected, 1 xfailed, 1 xpassed in 210.70s (0:03:30) ============================================================
nox > Command python -m pytest -k 'html and not ninja' -- doc gcovr failed with exit code 1
nox > Session tests_compiler(gcc-13) failed.
nox > Ran multiple sessions:
nox > * tests: success
nox > * tests_compiler(gcc-13): failed

**Comment by Spacetown** [comment]
This seems now to be a mismatch between the pygments version. Are you running the command on main or on a branch with modifications?

**Comment by ajpenner** [comment]
I am running on the main branch.

**Comment by Spacetown** [comment]
This test with the symlinks where failing in the CI. I fixed them to create the junction correct but it seems that it isn't working on your machine. I don't have a Windows machine to test this and have to rely on the CI.

**Comment by Spacetown** [comment]
Not reproducible in my environment.
